WebApplication1/WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/WebApplication1/Models/Player.cs
namespace WebApplication1.Models
{
    public class Player
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PCountry { get; set; }
        public string PType { get; set; }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/WebApplication1/Controllers/PlayersController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{

    public class PlayersController : Controller
    {
        static List<Player> players = new List<Player>()
    {
        new Player(){PId=1,PName="Rohit",PCountry="India",PType="Batsman"},
        new Player(){PId=2,PName="Virat",PCountry="India",PType="Batsman"},
        new Player(){PId=3,PName="Maxwell",PCountry="Aus",PType="All-Rounder"},
        new Player(){PId=4,PName="Dhoni",PCountry="India",PType="WK/Bat"},
        new Player(){PId=5,PName="K.L.Rahul",PCountry="India",PType="Batsman"},
    };
        public IActionResult Index()
        {
            return View(players);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new Player());
        }
        [HttpPost]
        public IActionResult Create(Player pla)
        {
            if (ModelState.IsValid)
            {
                players.Add(pla);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">We Have Players from these countries</h1>
    <p>List of Cricket Players</p>
</div>

WebApplication1/WebApplication1/Views/Players/Create.cshtml
@model WebApplication1.Models.Player

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Player</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PId" class="control-label"></label>
                <input asp-for="PId" class="form-control" />
                <span asp-validation-for="PId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PName" class="control-label"></label>
                <input asp-for="PName" class="form-control" />
                <span asp-validation-for="PName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PCountry" class="control-label"></label>
                <input asp-for="PCountry" class="form-control" />
                <span asp-validation-for="PCountry" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PType" class="control-label"></label>
                <input asp-for="PType" class="form-control" />
                <span asp-validation-for="PType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication1/WebApplication1/Views/Players/Index.cshtml
@model IEnumerable<WebApplication1.Models.Player>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PCountry)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PCountry)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PType)
            </td>
            
        </tr>
}
    </tbody>
</table>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>